template_path: sqs.yaml
stack_name: sqs-fargate-consumer-v2-high-priority
parameters:
  ScProductVersion: 1.0.9
  QueueName: "sqs-fargate-consumer-v2-high"
  VisibilityTimeout: "300"
  MaxReceiveCount: "10"
  CustomPolicyJSON: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "EventBridgeToSqsHighPriority",
          "Effect": "Allow",
          "Principal": {
            "Service": "events.amazonaws.com"
          },
          "Action": "sqs:SendMessage",
          "Resource": "arn:aws:sqs:us-west-2:982600293865:sqs-fargate-consumer-v2-high",
          "Condition": {
            "ArnEquals": {
              "aws:SourceArn": "arn:aws:events:us-west-2:982600293865:rule/gd-rg0-dev-rfd-events/domains-high-priority-events"
            }
          }
        }
      ]
    }
  # DeadLetterTargetArn: !stack_output_external sqs-fargate-consumer-v2-high-priority-dlq::QueueArn